{% set name = "mlconjug3" %}
{% set version = "3.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlconjug3-{{ version }}.tar.gz
  sha256: bed22e3b3a3850d04e7f690f5110fc0e11bdbee5a8a0d0b3193d953b3985d05c

build:
  number: 0
  noarch: python
  entry_points:
    - mlconjug3=mlconjug3.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - click >=8.0.3
    - colorama
    - cython
    - defusedxml
    - joblib
    - numpy
    - python >=3.7
    - scikit-learn >=1.0
    - scipy
    - progressbar2

test:
  imports:
    - mlconjug3
  commands:
    - pip check
    - mlconjug3 --help
  requires:
    - pip

about:
  home: https://github.com/SekouDiaoNlp/mlconjug3
  summary: A Python library to conjugate French, English, Spanish, Italian, Portuguese and Romanian verbs using Machine Learning techniques.
  license: MIT
  license_file: LICENSE
  description: |
    A Python library to conjugate verbs in French, English, Spanish, Italian, Portuguese and Romanian (more soon) using Machine Learning techniques.

    Any verb in one of the supported language can be conjugated, as the module contains a Machine Learning model of how the verbs behave.

    Even completely new or made-up verbs can be successfully conjugated in this manner.

    The supplied pre-trained models are composed of:

    -   a binary feature extractor,
    -   a feature selector using Linear Support Vector Classification,
    -   a classifier using Stochastic Gradient Descent.

    MLConjug3 uses scikit-learn to implement the Machine Learning algorithms.

    Users of the library can use any compatible classifiers from scikit-learn to modify and retrain the models.

    The training data for the french model is based on Verbiste https://perso.b2b2c.ca/~sarrazip/dev/verbiste.html .

    The training data for English, Spanish, Italian, Portuguese and Romanian was generated using unsupervised learning techniques using the French model as a model to query during the training.

    WARNING
    ========

    MLCONJUG3 now only supports Python 3.x as Python 2.x has been deprecated in 2020.

    Free software: MIT license

    Documentation: https://mlconjug3.readthedocs.io.

    SUPPORTED LANGUAGES:

    -   French
    -   English
    -   Spanish
    -   Italian
    -   Portuguese
    -   Romanian

    FEATURES:

    -   Easy to use API.
    -   Includes pre-trained models with 99% + accuracy in predicting conjugation class of unknown verbs.
    -   Easily train new models or add new languages.
    -   Easily integrate MLConjug in your own projects.
    -   Can be used as a command line tool.

    Usage
    =====

    > **note**
    >
    > The default language is French.
    > :   When called without specifying a language, the library will try to
    >     conjugate the verb in French.
    >
    To use MLConjug3 from the command line:

        $ mlconjug3 manger

        $ mlconjug3 bring -l en

        $ mlconjug3 gallofar --language es

        $ mlconjug3 -o, --output (Path of the filename for storing the conjugation tables.)

        $ mlconjug3 -s, --subject (The subject format type for the conjugated forms). The
                           values can be 'abbrev' or 'pronoun'. The default value
                           is 'abbrev'.

        $ mlconjug3 -h Show the help menu
  doc_url: https://mlconjug3.readthedocs.io/en/latest/
  dev_url: https://github.com/SekouDiaoNlp/mlconjug3

extra:
  recipe-maintainers:
    - SekouDiaoNlp
